server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

# scrape_configs:
#   - job_name: local
#     static_configs:
#     - targets:
#         - localhost
#       labels:
#         job: varlogs
#         __path__: /var/log/*log

scrape_configs:
  - job_name: docker-logs
    pipeline_stages:
    - docker: {}
    static_configs:
    - targets: # tells promtail to look for the logs on the current machine/host
        - localhost
      labels: # labels with which all the following logs should be labelled
        job: container
        host: docker    # label-1
        __path__: /var/lib/docker/containers/*/*-json.log
        # __path__ denotes the path of the actual log file whose logs will be scraped
        # and shipped to loki indexed with the above labels